#!/usr/bin/env bash
# Installs nginx server
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
sudo sed -i 's/listen 80;/listen 80;/g' /etc/nginx/nginx.conf
sudo service nginx restart
