#!/usr/bin/env bash
# Installs nginx server
apt-get update
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
sudo service nginx start
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
