#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS as well
# Format: The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO
while IFS= read -r line
do
echo "$line" | awk -F: '{print "The user " $1 " is part of the " $4 " gang, lives in " $6 " and rides " $7 ". " $3 "\x27s  place is protected by the passcode " $2", more info about the user here: " $5}'
done < /etc/passwd
