#!/usr/bin/env bash
# a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while [ $i -ne 10 ]
do
	i=$((i+1))
	echo "Best School"
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		:
	fi
done
