#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
i=0
while [ $i -ne 10 ]
do
	i=$((i+1))
	if [ $i -eq 4 ]
		then
			echo "bad luck"
	elif [ $i -eq 8 ]
		then
			echo "good luck"
	else
		echo "Best School"
	fi
done
