#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59
i=0
while [ $i -lt 12 ]
do
	i=$((i+1))
	echo "hour: $((i - 1))"
	j=0
	while [ $j -lt 59 ]
	do
		j=$((j+1))
		#echo "$i"
		echo "$j"

	done
done
