#!/usr/bin/env bash
#  a Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed.
output=$(ls)
for i in $output; do
	echo "$i" | cut -d '-' -f2
done
